config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', :registrations => "custom_registrations" }
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :users
  resources :friendships
  resources :friend_requests, only: [:index, :create, :show, :destroy, :update]
  resources :friends
end

app/views/shared/_cancel_rq_btn_sm.html.erb
<div class="right cancel-sm">
  <%= button_to "Cancel Request",
                friend_request_path(rq),
                remote: true,
                :params => { :id => rq.id },
                method: :delete,
                class: "btn btn-outline-danger btn-sm" %>
</div>

app/views/shared/_comment_form.html.erb
<%= form_for(post.comments.build, url: post_comments_path(post.id), remote: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field comment-field">
    <%= f.text_area :content, placeholder: "Write a comment here...", class: "form-control" %>
    <%= f.hidden_field :post_id, value: post.id %>
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="comment-button-wrapper">
    <%= f.submit "Comment", class: "btn btn-primary btn-sm comment-btn" %>
  </div>
<% end %>

app/views/shared/_comment_section.html.erb
<% post.comments.each do |comment| %>
  <div class="commentator">
    <% if comment.user.avatar.blob.filename == 'default.jpg' && comment.user.provider == 'facebook' %>
      <%= image_tag comment.user.remote_avatar, class: "comment-avatar" %>
    <% else  %>
      <%= image_tag comment.user.avatar.variant(resize: "32x32"), class: "comment-avatar" %>
    <% end %>
    <%= link_to comment.user.name, 
                user_path(comment.user), 
                class: "commentator-name" %>
                <i class="far fa-comment"></i>
    <% if comment.user == current_user %>  
      <%= render 'shared/delete_comment', comment: comment, post: post %>
    <% end %>
  </div>
  <span class="comment-content"> > <%= comment.content %></span>
<% end %>
<div class="write-comments">
  <%= render 'shared/comment_form', post: post %>
</div>

app/views/shared/_delete_comment.html.erb
<%= form_for( comment, 
              method: :delete,
              remote: true,
              url: post_comment_path(post.id, comment.id)) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    <%= button_tag  class: "btn btn-sm delete-comment-btn",
                  data: { confirm: 'Are you sure you want to delete this comment?' },
                  alt: 'Delete Comment' do %>
    <i class="far fa-trash-alt"></i>
  <% end %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_like_button.html.erb
<%= form_for( post.likes.build, 
              url: post_likes_path(post.id), 
              remote: true) do |f| %>
  <div><%= hidden_field_tag :user_id, current_user.id %></div>
  <%= button_tag class: "btn btn-outline-primary btn-sm like-btn" do %>
    <%= icon('fas', 'thumbs-up') + " Like" %> 
  <% end %>
<% end %>

app/views/shared/_like_button_area.html.erb
<div class="like-button-container">
  <span class="like-button" id="like-form<%= post.id %>">
  <% if !post.likes.where('user_id = ?', current_user.id).blank? %>
    <%= render 'shared/unlike_button', post: post %>
  <% else %>
    <%= render 'shared/like_button', post: post %>
  <% end %>
  </span>
  <span class="like-count" id="likers-<%="#{post.id}"%>">
    <% unless post.likes.count == 0 %>
      <%= "#{pluralize(post.likes.count, 'person')} liked this" %>
    <% end %>
  </span>
</div>

app/views/shared/_post.html.erb
<div class="post-container">
  <%= render 'shared/post_author_section', post: post %>
  <%= render 'shared/post_time', post: post %>
  <%= render 'shared/post_content', post: post %>
  <%= render 'shared/like_button_area', post: post %>
  <div class="under-line"></div>
  <div class="comment-box" id="comment-<%=post.id%>">
    <%= render 'shared/comment_section', post: post %>
  </div>
</div>

app/views/shared/_post_author_section.html.erb
<div class="author-info">
  <% if post.user.avatar.blob.filename == 'default.jpg' && post.user.provider == 'facebook' %>
    <%= image_tag post.user.remote_avatar, class: "small-avatar" %>
  <% else  %>
    <%= image_tag post.user.avatar.variant(resize: "40x40"), class: "small-avatar" %>
  <% end %>
  <%= link_to post.user.name, user_path(post.user), class: "author-name" %>
  <% if post.user == current_user %>
    <%= render 'shared/delete_post', post: post %>
  <% end %>
</div>

app/views/shared/_post_content.html.erb
<div class="post-content">

  <% if post.content.length < 50 %>
    <h3><%= post.content %></h2>
  <% else %>
    <%= post.content %>
  <% end %>
    <% if post.photo.attached? %>
    <%= image_tag post.photo, class: "img-fluid max-width: 500px" %>
  <% end %>
  <div class="above-line"></div>
</div>

app/views/shared/_post_form.html.erb
<%= form_for(@post, remote: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field post-writing">
    <%= f.text_area :content, placeholder: "What's on your mind today?...", class: "form-control"%>
    <%= f.file_field :photo, accept: 'image/png,image/gif,image/jpeg' %>
    <%= f.submit "Post", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/shared/_post_items.html.erb
<% unless posts.blank? %>
  <% posts.each do |post| %>
    <% unless post.id.nil? %>
      <%= render 'shared/post', post: post %>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_post_time.html.erb
<div class="post-time-container">
  <p class="post-time text-left"><%= time_ago_in_words(post.created_at) + " ago" %></p>  
</div>

app/views/shared/_unlike_button.html.erb
<%= form_for(current_user.likes.find_by(post_id: post.id),
             url: post_like_path(post.id, current_user.likes.find_by(post_id: post.id).id),
             html: { method: :delete },
             id: "like-#{post.id}",
             remote: true) do |f| %>
  <%= f.submit "Unlike", class: "btn btn-outline-primary btn-sm unlike-btn" %>
<% end %>