config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', :registrations => "custom_registrations" }
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :users
  resources :friendships
  resources :friend_requests, only: [:index, :create, :show, :destroy, :update]
  resources :friends
end

app/views/layouts/_flash.html.erb
<% if notice %>
  <div class="alert alert-notice col-md-8 offset-md-2">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-alert col-md-8 offset-md-2">
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
   FestBrooke by Punnadittr
  </small>
</footer>

app/views/layouts/_friend_request.html.erb
<li class="nav-item active dropdown">
    <a href="#" class="nav-link dropdown-toggle" 
                id="dropdownMenuButton" 
                data-toggle="dropdown" 
                aria-haspopup="true" 
                aria-expanded="false">
      <%= icon('fas', 'envelope')  %> Friend Requests
    </a>
    <div class="dropdown-menu-friend-request dropdown-menu" aria-labelledby="dropdownMenuButton">
      <% if current_user.received_friend_requests.blank? %>
        <div class="dropdown-item">
          <h6 class="center"> You currently have no requests </h5>
        </div>
      <% else %>
        <% current_user.received_friend_requests.limit(10).each do |rq| %>
          <div class="dropdown-item-friend-request dropdown-item">
            <div class="sender-name">
              <%= link_to rq.sender.shorten_name(12), user_path(rq.sender) %>
            </div>
            <div class="request-dropdown-button-wrapper">
              <div class="request-dropdown-ignore dropdown-btn">
                  <%= button_to "Ignore", 
                      friend_request_path(rq),
                      :params => { :id => rq.id },
                      method: :delete,
                      class: 'btn btn-light btn-sm ignore' %>
                </div>
              <div class="request-dropdown-accept dropdown-btn">
                <%= button_to "Accept",
                    friend_request_path(rq), 
                    :params => { :id => rq.id },
                    method: :put, 
                    class: 'btn btn-primary btn-sm accept' %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
      <div class="dropdown-divider-special dropdown-divider"></div>
      <div class="showall">
        <%= link_to 'Show All', friend_requests_path, class: "showall-text" %>
      </div>
    </div>
</li>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-primary">
  <%= link_to "fest_brooke", root_path, id: "logo", class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Users", users_path, class: "nav-link" %>
        </li>
        <%= render 'layouts/friend_request' %>
        <%= render 'layouts/profile_dropdown' %>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_profile_dropdown.html.erb
<li class="nav-item active dropdown mr-sm-2">
  <a  class="nav-link dropdown-toggle" 
      href="#" id="navbarDropdown" 
      role="button" 
      data-toggle="dropdown" 
      aria-haspopup="true" 
      aria-expanded="false">
    Account
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <%= link_to icon('fas', 'user-alt') + " Profile", 
                current_user, 
                class: "dropdown-item" %>
    <%= link_to icon('fas', 'user-friends') + " Friends", 
                friends_path, 
                class: "dropdown-item" %>
    <%= link_to icon('fas', 'cog') + " Settings", 
                edit_user_registration_path(current_user),
                class: "dropdown-item" %>
    <div class="dropdown-divider"></div>
     <%= link_to icon('fas', 'sign-out-alt') + " Log out", 
          destroy_user_session_path , 
          method: :delete, 
          id: 'logout-button',
          class: "dropdown-item" %>
  </div>
</li>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div id="flash">
        <%= render 'layouts/flash' %>
      </div>
      <%= yield %>
      <%= render 'layouts/footer'%>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>